/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DonorService } from "../donor.service";
import { DonorCreateInput } from "./DonorCreateInput";
import { Donor } from "./Donor";
import { DonorFindManyArgs } from "./DonorFindManyArgs";
import { DonorWhereUniqueInput } from "./DonorWhereUniqueInput";
import { DonorUpdateInput } from "./DonorUpdateInput";
import { DonationFindManyArgs } from "../../donation/base/DonationFindManyArgs";
import { Donation } from "../../donation/base/Donation";
import { DonationWhereUniqueInput } from "../../donation/base/DonationWhereUniqueInput";

export class DonorControllerBase {
  constructor(protected readonly service: DonorService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Donor })
  async createDonor(@common.Body() data: DonorCreateInput): Promise<Donor> {
    return await this.service.createDonor({
      data: data,
      select: {
        bloodType: true,
        createdAt: true,
        email: true,
        id: true,
        name: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Donor] })
  @ApiNestedQuery(DonorFindManyArgs)
  async donors(@common.Req() request: Request): Promise<Donor[]> {
    const args = plainToClass(DonorFindManyArgs, request.query);
    return this.service.donors({
      ...args,
      select: {
        bloodType: true,
        createdAt: true,
        email: true,
        id: true,
        name: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Donor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async donor(
    @common.Param() params: DonorWhereUniqueInput
  ): Promise<Donor | null> {
    const result = await this.service.donor({
      where: params,
      select: {
        bloodType: true,
        createdAt: true,
        email: true,
        id: true,
        name: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Donor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDonor(
    @common.Param() params: DonorWhereUniqueInput,
    @common.Body() data: DonorUpdateInput
  ): Promise<Donor | null> {
    try {
      return await this.service.updateDonor({
        where: params,
        data: data,
        select: {
          bloodType: true,
          createdAt: true,
          email: true,
          id: true,
          name: true,
          phoneNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Donor })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDonor(
    @common.Param() params: DonorWhereUniqueInput
  ): Promise<Donor | null> {
    try {
      return await this.service.deleteDonor({
        where: params,
        select: {
          bloodType: true,
          createdAt: true,
          email: true,
          id: true,
          name: true,
          phoneNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/donations")
  @ApiNestedQuery(DonationFindManyArgs)
  async findDonations(
    @common.Req() request: Request,
    @common.Param() params: DonorWhereUniqueInput
  ): Promise<Donation[]> {
    const query = plainToClass(DonationFindManyArgs, request.query);
    const results = await this.service.findDonations(params.id, {
      ...query,
      select: {
        bloodRequest: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        donationDate: true,

        donor: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/donations")
  async connectDonations(
    @common.Param() params: DonorWhereUniqueInput,
    @common.Body() body: DonationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      donations: {
        connect: body,
      },
    };
    await this.service.updateDonor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/donations")
  async updateDonations(
    @common.Param() params: DonorWhereUniqueInput,
    @common.Body() body: DonationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      donations: {
        set: body,
      },
    };
    await this.service.updateDonor({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/donations")
  async disconnectDonations(
    @common.Param() params: DonorWhereUniqueInput,
    @common.Body() body: DonationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      donations: {
        disconnect: body,
      },
    };
    await this.service.updateDonor({
      where: params,
      data,
      select: { id: true },
    });
  }
}
